# Generated by Django 4.1.3 on 2023-01-22 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Type name')),
            ],
        ),
        migrations.CreateModel(
            name='SupportAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name="Sender's first name")),
                ('last_name', models.CharField(max_length=255, verbose_name="Sender's last name")),
                ('email', models.EmailField(max_length=255, verbose_name="Sender's email")),
                ('phone_number', models.CharField(blank=True, max_length=75, null=True, verbose_name="Sender's phone number")),
                ('appeal_body', models.TextField(max_length=5000, verbose_name="Sender's appeal")),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.profile', verbose_name='Sender')),
            ],
        ),
        migrations.CreateModel(
            name='Nft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nft name')),
                ('img_link', models.CharField(max_length=255, verbose_name='Link to nft image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Nft price')),
                ('status', models.CharField(max_length=155)),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('opensea_link', models.CharField(max_length=255, unique=True)),
                ('deals_number', models.IntegerField()),
                ('monthly_roi', models.DecimalField(decimal_places=2, max_digits=14)),
                ('last_sale_date', models.DateTimeField()),
                ('max_profit_per_sale', models.DecimalField(decimal_places=2, max_digits=14)),
                ('min_profit_sale', models.DecimalField(decimal_places=2, max_digits=14)),
                ('average_sale_duration', models.CharField(max_length=355, null=True)),
                ('average_hold_duration', models.CharField(max_length=355, null=True)),
                ('royalty', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Royalty percent')),
                ('buy_link', models.CharField(max_length=255, verbose_name='Link to buy nft')),
                ('nft_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nft_type', to='home.nfttype', verbose_name='Type of nft')),
            ],
        ),
    ]
