# Generated by Django 4.1.3 on 2023-01-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=155)),
                ('price', models.DecimalField(decimal_places=5, max_digits=12, null=True, blank=True)),
                ('date', models.DateField(auto_now_add=False, null=True, blank=True)),
            ],
        ),
    ]
